server:
  port: 8761 #Eureka Server服务的端口号
eureka:
  instance:
    hostname: localhost #Eureka Server的hostname为localhost
  client:
    register-with-eureka: false #当前服务不需要到Eureka Server
    fetch-registry: false